---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "postgresql.fullname" . }}
  name: {{ include "postgresql.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 5432
  selector:
    app: {{ include "postgresql.fullname" . }}
