apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "nexus.fullname" . }}
  labels:
{{ include "nexus.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ include "nexus.fullname" . }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ include "nexus.fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: nexus-data
          mountPath: /nexus-data
        - name: nexus-script
          mountPath: /mnt
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-xc", "{
                while true; do
                  /mnt/initialize_nexus_repos.sh
                    --connection_check
                    --url http://127.0.0.1:{{ .Values.service.targetPort }} && break;
                  sleep 10;
                done &&
                ADMIN_PASSWORD=$(/usr/bin/cat /nexus-data/admin.password) &&
                /mnt/initialize_nexus_repos.sh
                  --user admin
                  --password $ADMIN_PASSWORD
                  --new_admin_password {{ .Values.newAdminPassword }}
                  --url http://127.0.0.1:{{ .Values.service.targetPort }} &&
                /mnt/initialize_nexus_repos.sh
                  --user admin
                  --password {{ .Values.newAdminPassword }}
                  --url http://127.0.0.1:{{ .Values.service.targetPort }}
                ;} &> /tmp/init.log"]
        livenessProbe:
          failureThreshold: 4
          httpGet:
            path: /
            port: {{ .Values.service.targetPort }}
            scheme: HTTP
          initialDelaySeconds: 300
          periodSeconds: 4
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /
            port: {{ .Values.service.targetPort }}
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 2
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 1900Mi
          requests:
            cpu: 200m
            memory: 1900Mi
      initContainers:
      - name: prepare-data-volume
        image: alpine:latest
        command:
          - /bin/sh
          - -c
          - chown -R 200:200 /nexus-data; rm -rf /nexus-data/lost+found
        volumeMounts:
        - mountPath: /nexus-data
          name: nexus-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nexus-data
        persistentVolumeClaim:
          claimName: {{ include "nexus.fullname" . }}-pv-claim
      - name: nexus-script
        configMap:
          name: initialize-nexus-repos-script
          defaultMode: 0755
