---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "nexus.fullname" . }}
  name: {{ include "nexus.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ include "nexus.fullname" . }}
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "nexus.fullname" . }}
  name: {{ include "nexus.fullname" . }}-registry
spec:
  type: ClusterIP
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: {{ include "nexus.fullname" . }}
  sessionAffinity: None
