---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "jenkins.fullname" . }}-pv-claim
  labels:
    app: {{ include "jenkins.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 5Gi

