---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "jenkins.fullname" . }}
  name: {{ include "jenkins.fullname" . }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ include "jenkins.fullname" . }}
  sessionAffinity: None
  type: {{ .Values.service.type }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "jenkins.fullname" . }}
  name: {{ include "jenkins.fullname" . }}-jnlp
spec:
  ports:
  - port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    app: {{ include "jenkins.fullname" . }}
  sessionAffinity: None
  type: ClusterIP

