---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "application-namespace.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  - hosts:
    - {{ .Values.fqdn }}
    secretName: {{ .Values.ingress.tls.secretName }}
  rules:
  - host: {{ .Values.fqdn }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.service.name }}
          servicePort: {{ .Values.service.port }}
        path: /(.*)
